"""Types for the staff assistant.

Shape of the data flowing through the system:

  Event   →  RoomState   →  Prediction   →  ActionCard

* Event: external signal — door open/close, checkin, food order, flight update.
* RoomState: per-room running summary, mutated by events.
* Prediction: derived numbers (return time, cleaning window, etc.).
* ActionCard: human-readable line shown on the staff board, written by Haiku.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, TypedDict

EventType = Literal[
    "checkin",
    "checkout",
    "door_open",
    "door_close",
    "food_order",
    "flight_update",
]

CardType = Literal["housekeeping", "room_service", "arrival"]
Urgency = Literal["info", "soon", "now"]


class Event(TypedDict):
    room: str
    type: EventType
    ts: float                 # unix seconds
    payload: dict             # type-specific: e.g. {"order_id":..,"items":..}


@dataclass
class RoomState:
    room: str
    family_id: str | None = None
    in_room: bool = False
    last_door_ts: float | None = None
    last_door_kind: Literal["open", "close"] | None = None
    current_slot_idx: int | None = None         # 0..29 over the 5-day trip
    next_planned_activity: str | None = None
    expected_return_ts: float | None = None
    pending_food_order: dict | None = None      # {"items": [...], "target_ts": ...}
    arrival_flight: str | None = None           # IATA flight code
    arrival_eta_ts: float | None = None
    events: list[Event] = field(default_factory=list)


@dataclass
class Prediction:
    """Heuristic outputs the narrator turns into staff actions."""
    room: str
    now_ts: float
    in_room: bool
    expected_return_ts: float | None
    cleaning_window_min: int | None         # minutes available to clean
    cleaning_recommendation: Literal["go-now", "quick-turn", "skip", "in-room"]
    food_cook_start_ts: float | None        # when to start cooking pending order
    food_deliver_ts: float | None           # when to bring it to the door
    arrival_eta_ts: float | None            # for not-yet-arrived guests
    arrival_setup_ts: float | None          # when fruit/welcome must be in place
    raw: dict = field(default_factory=dict) # bag for narrator context


@dataclass
class ActionCard:
    """One line on the staff board, generated by Haiku."""
    room: str
    type: CardType
    urgency: Urgency
    action_line: str           # short imperative — what to do
    reasoning: str             # 2-sentence "why" for the click-through
    deadline_ts: float | None  # for sorting; None = informational
